import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Worqhat-TxtToCode',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}


//layout.js
// import './globals.css';
// import Editor from '@monaco-editor/react'

// import { useEffect } from 'react';
// import { Editor } from '@monaco-editor/react';

// export default function CodeEditor({ editorRef }) {
//   useEffect(() => {
//     if (editorRef.current) {
//       editorRef.current.focus();
//     }
//   }, []);
  
// function App() {
//   const [fileName, setFileName] = useState("script.js");
//   const editorRef= useRef(null)
//   const file= files[fileName]
//   function handleEditorDidMount(editor,monaco){
//     editorRef.current=editor
//   }
//   return (
//     <>
//       <html lang="en">
//         <head>
//           <meta charset="UTF-8" />
//           <meta http-equiv="X-UA-Compatible" content="IE=edge" />
//           <meta name="viewport" content="width=device-width, initial-scale=1.0" />
//           <title>TxtToCode</title>
//         </head>
//         <body>
//           <div className="container">
//             <h1>Text to Code Generator</h1>
//             <input type="text" id="textbox1" placeholder="Enter your text" />
//             <div>
//               <select id="language">
//                 <option value="">Select language</option>
//                 <option value="cpp">C++</option>
//                 <option value="python">Python</option>
//                 <option value="java">Java</option>
//                 <option value="javascript">JavaScript</option>
//                 <option value="php">PHP</option>
//               </select>
//             </div>
//             <button id="generateButton">Generate Code</button>
//             <input type="text" id="textbox2" placeholder="Generated code will appear here" />
//             <div>
//             <Editor
//       height="200px"
//       width="500px"
//       theme="vs-dark"
//       defaultLanguage="python"
//       ref={editorRef}
//     />
//             </div>
//           </div>
//         </body>
//       </html>
//     </>
//   );
// }
// export default App()




//page.js
// import Image from 'next/image'

// export default function Home() {
//   return (
//     <main className="flex flex-col items-center justify-between p-24">
//           <a
//             className="pointer-events-none flex place-items-center gap-2 p-8 lg:pointer-events-auto lg:p-0"
//             href="https://www.worqhat.com/"
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             By{' '}
//             <Image
//               class="logo"
//               src="/worqhatlogo.png"
//               alt="Vercel Logo"
//               className="dark:invert"
//               width={100}
//               height={30}
//               priority
//             />
//           </a>
       
//     </main>
//   )
// }